spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/db;
    username: sa
    password: 1145
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true
        #show_sql: true
        format_sql: true

logging:
  level:
    #    org.hibernate: debug
    org.hibernate.stat: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
#    org.hibernate.type: trace