spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/db;
    username: sa
    password: 1145
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB

  profiles:
    include: "auth"

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true
        #show_sql: true
        format_sql: true

logging:
  level:
    #    org.hibernate: debug
    org.hibernate.stat: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
#    org.hibernate.type: trace
